local:
  script:
    - bash build.sh local
  tags:
    - local
  when: manual

test:
  script:
    - bash build.sh test
  tags:
    - test
  when: manual

public:
  script:
    - bash build.sh public
  tags:
    - public
  when: manual

product:
  script:
    - bash build.sh product
  tags:
    - product

echo:
  script:
    - d=$(date -u +"%Y-%m-%dT%H%M%SZ")
    - dir=/tmp/gitlab-ci/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}/${CI_COMMIT_SHA}/
    - mkdir -pv ${dir}
    - touch ${dir}/${d}.txt
  tags:
    - echo
